# Generated by Django 5.0.4 on 2024-05-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendor_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="id",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="id",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivered_data",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_code",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
